Create from description command
Welltested-AI/fluttergpt pull request #27
Opened 2023-04-29 20:19 UTC by maxim-saplin

Thanks for the nice extension! I've added a new command which I missed while using the extension - ability to create code via a prompt and have it inserted at the current cursor location. Please not that my version also added the concept of context and puts surrounding code to the prompt.

2023-05-01 10:30 UTC, samyakkkk requested changes
hey @maxim-saplin! thanks for bringing in your ideas on table. 

I tried it out and looks good :) the existing `codeFromBlueprint` function we have can be tuned to do the same but I think your code to add the context along with the instructions brings more value to this case. 

Would love to merge and push this in the next release. Just left some minor change requests. Please address them. 
 
Thanks!

2023-05-01 10:30 UTC, samyakkkk commented on src/tools/create/code_from_description.ts
> +            let prompt = `You're an expert Flutter developer. Follow the instructions carefully and to the letter.\n\n`;
```suggestion
            let prompt = `You're an expert Flutter/Dart coding assistant. Follow the user instructions carefully and to the letter.\n\n`;
```
Keeping the identity consistent across all platforms.

2023-05-01 10:30 UTC, samyakkkk commented on package.json
> +        "command": "fluttergpt.createCodeFromDescription.menu",
Register this in `fluttergpt.createMenu` as well so the command is also accessible via right-click menu under FlutterGPT: Create section.

2023-05-01 21:08 UTC, maxim-saplin commented
Thanks for the quick reply and review. I hope I didn't miss anything in the updates I just did

2023-05-03 09:47 UTC, samyakkkk commented
Thanks @maxim-saplin, merging this. It will go in the next release!

2023-05-03 09:47 UTC, merged